version: "3.7"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "1299:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "YES"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"

volumes:
  mysql-data:
